name: Gemini AI Code Reviewer

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions: write-all

jobs:
  gemini-code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get PR Details
        id: pr
        run: |
          PR_JSON=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }})
          echo "head_sha=$(echo $PR_JSON | jq -r .head.sha)" >> $GITHUB_OUTPUT
          echo "base_sha=$(echo $PR_JSON | jq -r .base.sha)" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: Swisyn/gemini-ai-code-reviewer@v1.0.0
        with:
          GITHUB_API_URL: "https://api.github.com" # Updated to standard GitHub API if you aren't on GitHub Enterprise
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GEMINI_MODEL: "gemini-2.5-pro-preview-05-06"
          EXCLUDE: "*.md,*.txt,package-lock.json,*.yml,*.yaml"
